### ISSUE TITLE
PIN not working

### ISSUE THREAD

**Issue by emjhay2004** [Ralex91/Rahoot#3]
Hi, I have passed by your repository and looks promising, but however PIN does not work.

I have:
Ubuntu Server 22.04
Node.js v18.19.1

**Comment by Ralex91** [comment]
Hello @emjhay2004!

I'm sorry, but I haven't yet produced a documentation on how to use Rahoot!

I think you're confusing the password in the socket config with the PIN code.
(config socket is here : https://github.com/Ralex91/Rahoot/blob/main/socket/quizz.config.js)

The password in the socket config is used to access the manager side to go to the manager page, go to http://localhost:3000/manager then enter the config password, and you'll be redirected to a page with the PIN code that players must use to join.

Have you installed the dependencies correctly?

Did you run the script commands in the package.json file?
For dev:
```npm run all-dev```

For prod
```npm run all```

**Comment by emjhay2004** [comment]
Hi,

Yes, I tried to:
`npm install`

on the Rahoot directory and:
`npm i sharp`

for Image Optimization

The only this I am missing is the links where to go and you point me to the right direction, will try the link you provided.

The reason why I am looking here in github is Kahoot and Quizizz are no longer available for free use and they are limiting the free to previous created quiz, new quiz requires some subscription. So that is the reason I am looking for an alternative to Kahoot and Quizizz.

**Comment by emjhay2004** [comment]
I am getting a problem with websocket
<img width="702" alt="image" src="https://github.com/Ralex91/Rahoot/assets/58817065/c502814e-b783-4281-a945-0cf6c4a74ccf">

It seems that websocket host is localhost, wherein I hosted it on my VirtualBox environment, Ubuntu Server 22.04, Node.js v18.19.1.

**Comment by emjhay2004** [comment]
I now found where to edit the websocket, it is at:

> src/constants.js
> 
> export const WEBSOCKET_URL = "http://localhost:5157"

**Comment by emjhay2004** [comment]
It seems that the Rahoot is now functional, the lacking functionality is leaderboard for all participants like in Kahoot where it displays the score of all participants including their incorrect and correct answers, timing of their submission, etc...

**Comment by Ralex91** [comment]
I apologize for the lack of explanations on how to install and use Rahoot, as it's a project I did quite quickly in a short space of time. I didn't have the courage to make a README, but I'll try to do one when I have the time.


I made this Kahoot clone because I didn't feel like creating an account and paying for it, and I wanted to make a project as quickly as possible to test my skills.

**Comment by emjhay2004** [comment]
> I apologize for the lack of explanations on how to install and use Rahoot, as it's a project I did quite quickly in a short space of time. I didn't have the courage to make a README, but I'll try to do one when I have the time.
> 
> I made this Kahoot clone because I didn't feel like creating an account and paying for it, and I wanted to make a project as quickly as possible to test my skills.

Well, I'll support your project with this one, in anyway I can... Surely we want a better functional online quiz like Kahoot...
